# changed
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: whoami-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     # traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
# spec:
#   rules:
#   - host: csky08
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: whoami-service
#           servicePort: 80


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: csky08
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-service
            port:
              number: 80