apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This will add annotation under every metadata entry
# ex: main metadata, spec.metadata etc
commonLabels:
  author: nirgeier@gmail.com
  env: qa
  version: v1
bases:
  - ../_base
